version: '3'

networks:
    app-network:
        driver: bridge

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    db:
        image: mysql:8.0
        ports:
            - "33060:3306"
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network
